### ISSUE TITLE
Does this pedersen_hash function implement the real pedersen hash algorithm?

### ISSUE THREAD

**Issue by Senlody** [Electric-Coin-Company/jubjub-prototype#8]
Seems that the code is different from g1^x1*g2^x2* ...* gn^xn.
Is it just a "dummy" version for benchmark?

**Comment by daira** [comment]
The hash that we intend to implement is described in section 3.4 of https://groups.csail.mit.edu/cis/pubs/shafi/1994-lncs.pdf , adapted to an elliptic curve and with the message encoding function specified in https://github.com/zcash/zcash/issues/2234#issuecomment-334121434 , but using 4-bit rather than 5-bit windows. I believe the current prototype differs from this by not implementing the negation optimisation, and taking the y-coordinate of the result rather than the x-coordinate.

**Comment by daira** [comment]
We ended up using 3-bit windows. The current implementation matches sections 5.4.1.7 and A.3.3.9 of the spec.
